
### 회원가입
POST http://localhost:3000/api/signup
Content-Type: application/json

{  
    "nickname": "Tester1",  
    "password": "12345",  
    "confirm": "12345"
}
    
### 로그인
POST http://localhost:3000/api/login
Content-Type: application/json

{  
    "nickname": "Tester1",
    "password": "12345"
}

### 받은 토큰 예시 
### { "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1OTA3ODMzNn0.vFDvYP2DAIqnRcPD6WyppqXHm72lfgD_PO3-jSV-6Xw"}

###

### 게시글 작성 셍성 
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1OTA3ODMzNn0.vFDvYP2DAIqnRcPD6WyppqXHm72lfgD_PO3-jSV-6Xw

{
    "title": "안녕하세요",
    "content": "이런저런 글입니다24444 안녕히계세요~~"
}
    
    
### 게시글 모두 조회 불러오는 (주소창)
GET http://localhost:3000/api/posts

### 특정 게시글 상세 조회
GET http://localhost:3000/api/posts/6

### 게시글 수정 
PUT http://localhost:3000/api/posts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1OTA3ODMzNn0.vFDvYP2DAIqnRcPD6WyppqXHm72lfgD_PO3-jSV-6Xw

{ 
    "title": "안녕하세요3",
    "comment": "안녕하세요 댓글입니다."
}

### 게시글 삭제
DELETE http://localhost:3000/api/posts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1OTA3ODMzNn0.vFDvYP2DAIqnRcPD6WyppqXHm72lfgD_PO3-jSV-6Xw

{ 
    "password": "12d34"
}	


### 특정 게시글에 댓글 작성   // 사용중인 유저로 진행 필요
POST http://localhost:3000/api/comments/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1OTA3ODMzNn0.vFDvYP2DAIqnRcPD6WyppqXHm72lfgD_PO3-jSV-6Xw

{
    "comment": "안녕하세요 댓글입니다."
}
    
### 특정 게시글의 댓글 조회
GET http://localhost:3000/api/comments/6

### 댓글 수정
PUT http://localhost:3000/api/comments/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1OTA3ODMzNn0.vFDvYP2DAIqnRcPD6WyppqXHm72lfgD_PO3-jSV-6Xw

{ 
    "comment": "안녕하세요 수정된 댓글입니다."
}

### 댓글 삭제 
DELETE http://localhost:3000/api/comments/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1OTA3ODMzNn0.vFDvYP2DAIqnRcPD6WyppqXHm72lfgD_PO3-jSV-6Xw


