
### 게시글 작성 셍성
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "user": "김보현",
    "password": "12d34",
    "title": "안녕하세요",
    "content": "이런저런 글입니다24444 안녕히계세요~~"
}
    
    
### 게시글 모두 조회 불러오는 (주소창)
GET http://localhost:3000/api/posts

### 특정 게시글 상세 조회
GET http://localhost:3000/api/posts/62e25c5b91daa64cdb807e4f  

### 게시글 수정
PUT http://localhost:3000/api/posts/62e25c5b91daa64cdb807e4f
Content-Type: application/json

{ 
    "password": "1234",
    "title": "안녕하세요ㅇㅇㅇㅇㅇㅇ",
    "content": "이런저런 글입니다33333 안녕히계세요~~" 
}

### 게시글 삭제
DELETE http://localhost:3000/api/posts/62e25c5b91daa64cdb807e4f
Content-Type: application/json

{ 
    "password": "1234"
}	


### 특정 게시글에 댓글 작성 
POST http://localhost:3000/api/comments/62e25cc091daa64cdb807e56
Content-Type: application/json

{
    "user": "Developer",
    "password": "12345",
    "content": "ㅇㅋㅇㅋ"
}
    
### 특정 게시글의 댓글 조회
GET http://localhost:3000/api/comments/62e25cc091daa64cdb807e56

### 댓글 수정
PUT http://localhost:3000/api/comments/62e25d3991daa64cdb807e6d
Content-Type: application/json

{ 
    "password": "12345",
    "content": "ㅇㅇㅇㅇㅇㅇ" 
}

### 댓글 삭제 
DELETE http://localhost:3000/api/comments/62e25d3991daa64cdb807e6d
Content-Type: application/json

{ 
    "password": "12345"
}	



