
### 게시글 작성 셍성
POST http://nodeapi.myspaceti.me/api/posts
Content-Type: application/json

{
    "user": "김보현",
    "password": "12d34",
    "title": "안녕하세요",
    "content": "이런저런 글입니다24444 안녕히계세요~~"
}
    
    
### 게시글 모두 조회 불러오는 (주소창)
GET http://nodeapi.myspaceti.me/api/posts

### 특정 게시글 상세 조회
GET http://nodeapi.myspaceti.me/api/posts/62e1f0b0919b8fdbc14d0b13  

### 게시글 수정
PUT http://nodeapi.myspaceti.me/api/posts/62e1f0b0919b8fdbc14d0b13
Content-Type: application/json

{ 
    "password": "12d34",
    "title": "안녕하세요3",
    "content": "이런저런 글입니다33333 안녕히계세요~~" 
}

### 게시글 삭제
DELETE http://nodeapi.myspaceti.me/api/posts/62e1f0b0919b8fdbc14d0b13
Content-Type: application/json

{ 
    "password": "12d34"
}	


### 특정 게시글에 댓글 작성 
POST http://nodeapi.myspaceti.me/api/comments/62de7ccbceb3f499c2d2a7b9
Content-Type: application/json

{
    "user": "Developer",
    "password": "12345",
    "content": "ㅇㅋㅇㅋ"
}
    
### 특정 게시글의 댓글 조회
GET http://nodeapi.myspaceti.me/api/comments/62de7ccbceb3f499c2d2a7b9

### 댓글 수정
PUT http://nodeapi.myspaceti.me/api/comments/62e1f5b2a1f6849c8ed3a65e
Content-Type: application/json

{ 
    "password": "12345",
    "content": "ㅇㅇ" 
}

### 댓글 삭제 
DELETE http://nodeapi.myspaceti.me/api/comments/62e1f465919b8fdbc14d0b38
Content-Type: application/json

{ 
    "password": "1234"
}	



