
### 게시글 작성 셍성
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "user": "김보현",
    "password": "12d34",
    "title": "안녕하세요",
    "content": "이런저런 글입니다24444 안녕히계세요~~"
}
    
    
### 게시글 모두 조회 불러오는 (주소창)
GET http://localhost:3000/api/posts

### 특정 게시글 상세 조회
GET http://localhost:3000/api/posts/62e1e6e8e76f26ad11ec912c  

### 게시글 수정
PUT http://localhost:3000/api/posts/62e1e70ce76f26ad11ec9134
Content-Type: application/json

{ 
    "password": "12d34",
    "title": "안녕하세요3",
    "content": "이런저런 글입니다33333 안녕히계세요~~" 
}

### 게시글 삭제
DELETE http://localhost:3000/api/posts/62e1e6e8e76f26ad11ec912c
Content-Type: application/json

{ 
    "password": "12a34"
}	


### 특정 게시글에 댓글 작성 
POST http://localhost:3000/api/comments/62df792f437fe28248ee021d
Content-Type: application/json

{
    "user": "Developer",
    "password": "1234",
    "content": "ㅇㅋㅇㅋ"
}
    
### 특정 게시글의 댓글 조회
GET http://localhost:3000/api/comments/62df792f437fe28248ee021d

### 댓글 수정
PUT http://localhost:3000/api/comments/62e1e99b10eabc058cedf46f
Content-Type: application/json

{ 
    "password": "1234",
    "content": "ㅇㅇ" 
}

### 댓글 삭제 
DELETE http://localhost:3000/api/comments/62e1e99b10eabc058cedf46f
Content-Type: application/json

{ 
    "password": "1234"
}	



